import Image from "next/image";

import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const imgSrc = process.env.IMG_URL;
  return (
    <html lang="en">
      <body>
        <header className="bg-brand-primaryYellow">
          <Link
            className="pt-6 pb-2 flex items-center justify-center"
            href="/order"
          >
            <Image
              src={imgSrc}
              alt="logo"
              width={250}
              height={60}
              priority
              className="h-auto"
            />
          </Link>
        </header>
        <section className="w-full max-w-[550px] mx-auto relative">
          {children}
        </section>
      </body>
    </html>
  );
}
